Repository fofix/fofix, pull requests merged in 2019-07, with the labels that each got.

#197 Use platform.uname() instead of os.uname()
  setup.py
Labels: enhancement

#198 Clean up the Theme module
  fofix/core/Theme.py
Labels: cleanup, enhancement

#201 Vocalist: clean up the module
  fofix/game/guitarscene/instruments/Vocalist.py
Labels: cleanup
