Repository fofix/fofix, pull requests merged in 2020-06, with the labels that each got.

#185 Use Pillow version number
  fofix/core/GameEngine.py
Labels: dependencies, enhancement

#220 Bump Pillow from 6.2.0 to 6.2.2
  doc/source/misc/releasenotes.rst
  requirements.txt
Labels: dependencies

#221 Doc: update release notes after the 3.122 release
  doc/source/misc/releasenotes.rst
Labels: doc
