Repository fofix/fofix, pull requests merged in 2020-10, with the labels that each got.

#118 Refactor fofix.core.Config
  fofix/core/Config.py
Labels: cleanup, enhancement

#227 Tests: init tests for the core.Mesh module
  fofix/core/Mesh.py
  fofix/tests/core/test_mesh.py
Labels: doc, enhancement

#228 fix lobbyTitleTextPos to be properly cast as float
  fofix/core/Theme.py
Labels: enhancement
