Repository fofix/fofix, pull requests merged in 2021-05, with the labels that each got.

#189 fix non ascii song titles
  fofix/core/Config.py
Labels: enhancement, needs-work

#240 fix(config): encode the section value to utf-8
  fofix/core/Config.py
  fofix/tests/core/test_config.py
Labels: cleanup, enhancement

#241 chore(scenefactory): clean up the module
  fofix/core/SceneFactory.py
Labels: cleanup
