Repository fofix/fofix, pull requests merged in 2021-06, with the labels that each got.

#244 ci(python3): run optional tests and fail fast
  .github/workflows/tests.yml
Labels: dependencies, enhancement, feature

#242 test(font): test `Cache` and `Font` classes
  fofix/tests/core/test_font.py
Labels: enhancement

#245 How to: guide for Linux users
  README.md
  doc/source/quickstart/Linux_Setup_Guide.md
Labels: doc
